name = "juyitingweb"
compatibility_date = "2024-12-19"
compatibility_flags = ["nodejs_compat"]

# Pages 项目配置
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]